services:
  voice-auth-api:
    build: .
    container_name: voice_auth_container
    ports:
      - "8007:8000"
    volumes:
      # Persist the 'storage' folder (Audio + ChromaDB)
      - ./storage:/app/storage
    environment:
      - MONGO_URL=mongodb+srv://sherazrazaoctaloop:raza87654321@myfreecluster.k849b1v.mongodb.net/
    depends_on:
      - mongo_db

  voice-auth-client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://18.206.13.3:8007}
    container_name: voice_auth_client
    ports:
      - "8008:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://18.206.13.3:8007
    depends_on:
      - voice-auth-api

  mongo_db:
    image: mongo:latest
    container_name: voice_auth_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: